---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "26"
year: "2014"
contributor: 
- "Uwe Jung"
title: "Abstand als Alternative? Vom Normalen und weniger Normalen in kamerunischen Bibliotheken"
abstract: "Am praktischen Beispiel des kamerunischen Bibliothekswesens werden Probleme bei der Übernahme von 'traditionellen' Bibliothekskonzepten in andere Kulturen verdeutlicht. Die Lösungen dieser Probleme werden zum einen in einem besseren Verständnis der handelnden Akteure, zum anderen in einer Neuausrichtung der Zusammenarbeit mit eben diesen Akteuren gesehen."
subtitle: ""
urn: "urn:nbn:de:kobv:11-100222625"
date: 2014-12-15 22:00
comments: false
sharing: true
footer: true

---