---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "26"
year: "2014"
contributor: 
- "Ben Kaden"
title: "Konzepte für den Gegenwartsdiskurs. Heute: Linguistic Capitalism"
subtitle: ""
urn: "urn:nbn:de:kobv:11-100222668"
date: 2014-12-15 22:00
comments: false
sharing: true
footer: true

---