---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "26"
year: "2014"
contributor: 
- "Ben Kaden"
title: "Europa also Zone der Zines. Über eine Fahrbibliothek"
subtitle: ""
urn: ""
date: 2014-12-15 22:00
comments: false
sharing: true
footer: true

---