---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "26"
year: "2014"
contributor: 
- "Paul Vierkant"
- "Maxi Kindling"
title: "Welche Institutionen betreiben Open-Access-Repositorien in Deutschland?"
subtitle: ""
urn: "urn:nbn:de:kobv:11-100222687"
date: 2014-12-15 22:00
comments: false
sharing: true
footer: true

---