---

layout: page
lang: "en"
journal: "LIBREAS. Library Ideas"
issue: "26"
year: "2014"
contributor: 
- "Snowden Commons"
title: "From the Snowden Files to the Snowden Commons: The Library as a Civic Hub"
subtitle: ""
urn: "urn:nbn:de:kobv:11-100222989"
date: 2014-12-15 22:00
comments: false
sharing: true
footer: true

---