---

layout: page
lang: "en"
journal: "LIBREAS. Library Ideas"
issue: "26"
year: "2014"
contributor: 
- "Eliane Blumer"
- "Karsten Schuldt"
title: "Urban Revitalization, Gentrification, and the Public Library: The Case of Lausanne, Switzerland"
abstract: "Gentrification – a process of replacement of a poorer population in an urban neighborhood with a richer one and the change of the looks of this respective neighborhood – has become a widespread topic of societal debates in recent years. This process is linked to public art and cultural activities, and sometimes triggered with projects of urban revitalization by the respective cities. Public libraries are part of this process and they are used in the concepts of urban revitalization as well as institutions for public culture. This puts them in an uneasy position: thus, libraries also become part in processes of repulsion socially vulnerable groups. The text will discuss the current position of public libraries in respect to gentrification, using some incidents in the city of Lausanne, Switzerland, as a case study."
subtitle: ""
urn: "urn:nbn:de:kobv:11-100222616"
date: 2014-12-15 22:00
comments: false
sharing: true
footer: true

---