---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "26"
year: "2014"
contributor: 
- "Bibliothekskollektiv Anarchistische Bibliothek & Archiv Wien"
title: "Anarchistische Bibliothek & Archiv Wien"
subtitle: ""
urn: "urn:nbn:de:kobv:11-100222630"
date: 2014-12-15 22:00
comments: false
sharing: true
footer: true

---