---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "26"
year: "2014"
contributor: 
- "Christian Kahle"
title: "Die <i>Offene Bibliothek</i> von <i>Clegg & Guttmann</i>"
subtitle: ""
urn: "urn:nbn:de:kobv:11-100222672"
date: 2014-12-15 22:00
comments: false
sharing: true
footer: true

---