---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "26"
year: "2014"
contributor: 
- "Christian Kahle"
title: "Die <i>Offene Bibliothek</i> von <i>Clegg & Guttmann</i>"
subtitle: ""
urn: ""
date: 2014-12-15 22:00
comments: false
sharing: true
footer: true

---