---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "26"
year: "2014"
contributor: 
- "Redaktion LIBREAS"
title: "Editorial #26: Bibliotheken __abseits, außerhalb der Bibliothek"
subtitle: ""
urn: "urn:nbn:de:kobv:11-100222654"
date: 2014-12-15 22:00
comments: false
sharing: true
footer: true

---